# Generated by Django 3.2.6 on 2021-08-28 13:55

from django.db import migrations, models
import news.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('title', models.CharField(max_length=60)),
                ('text', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to=news.models.photo_upload)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
    ]
